from PIL import Image
# img = Image.open('image1.jpg')
# img1 = Image.open('newimage.jpg')
blue = Image.open('blue_color.jpg')
red = Image.open('red_color.jpg')
# print(img.size)
# crop_ =img.crop((100,750,1000,1498))
# rotate_ =img.rotate(90)
# resize_ =img.resize((1500,2000))
# img.paste(im=crop_,box=(0,0))
# img.putalpha(128)
red.putalpha(150)
blue.putalpha(100)
blue.paste(im=red,box=(0,0),mask=red)
blue.save('nyo_color.jpg')
new_ = Image.open('nyo_color.jpg')
new_.show()
